version: "3.7"

services:

  openproject:
    container_name: openproject
    build:
      context: openproject-ce
    ports:
      - 5432:5432
      - 8090:80

  gitbucket:
    container_name: gitbucket
    build: 
      context: gitbucket
    ports:
      - "8080:8080"
      - "29418:29418"

  drone-server:
    container_name: drone-server
    build: 
      context: drone-server
    ports:
      - "9000:9000"
      - "443:443"
    volumes:
      - "/drone:/var/lib/drone"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  drone-agent:
    container_name: drone-agent
    command: agent
    build:
      context: drone-agent
    depends_on:
      - drone-server
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker

#drone-server:
  #  container_name: drone-server
  #  image: drone/drone:1
  #  ports:
  #    - 8081:80
  #  volumes:
  #    - ./:/drone-github-demo/data
  #  restart: always
  #  environment:
   #   - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
  #    - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
   #   - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}

      # GitHub Config
   #   - DRONE_GITHUB_SERVER=https://github.com
   #   - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
  #    - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}

   #   - DRONE_LOGS_PRETTY=true
   #   - DRONE_LOGS_COLOR=true

  # runner for docker version
 # drone-runner:
  #  container_name: drone-runner
  #  image: drone/drone-runner-docker:1
  #  restart: always
  #  depends_on:
  #    - drone-server
  #  volumes:
   #   - /var/run/docker.sock:/var/run/docker.sock
   # environment:
  #    - DRONE_RPC_HOST=${DRONE_RPC_HOST}
  #    - DRONE_RPC_PROTO=${DRONE_RPC_PROTO}
  #    - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
  #    - DRONE_RUNNER_CAPACITY=3
